version: "3.7"

services:
  database_vuttr:
    image:  bitnami/mongodb:latest
    container_name: database_vuttr
    restart: always
    ports:
      - 27017:27017
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    volumes:
      - mongodata:/data/postgres
    networks:
      - app-network
  app:
    networks:
      - app-network
    build: .
    container_name: vuttr
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    
volumes:
  mongodata:
    driver: local

networks:
  app-network:
    driver: bridge